---
name: PoC Automated Vulnerability Remediation
permissions:
  contents: write
  security-events: write
  actions: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  trivy_scan_and_fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install PyYAML requests

      - name: Install Trivy and GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
          type gh >/dev/null 2>&1 || (curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && sudo apt-get update && sudo apt-get install -y gh)

      - name: Create Trivy reports directory
        run: mkdir -p trivy-reports

      - name: Build Docker Image (Initial)
        run: docker build -t go-app-vulnerable:latest ./go-app-vulnerable/

      - name: Initial Trivy Scan - All Vulnerability Types (JSON for script + SARIF)
        run: |
          trivy fs --format json --output trivy-reports/trivy-go-initial.json --severity CRITICAL,HIGH,MEDIUM,LOW go-app-vulnerable/
          trivy config --format json --output trivy-reports/trivy-dockerfile-initial.json --severity CRITICAL,HIGH,MEDIUM,LOW go-app-vulnerable/Dockerfile
          trivy image --format json --output trivy-reports/trivy-image-initial.json --severity CRITICAL,HIGH,MEDIUM,LOW go-app-vulnerable:latest
          trivy fs --format sarif --output trivy-reports/trivy-fs.sarif go-app-vulnerable/
        continue-on-error: true

      - name: Upload Initial Scan SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-reports/trivy-fs.sarif
        if: always()

      - name: Run Automated Remediation Script (Python)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/remediate_pipeline_poc.py \
            --go-report trivy-reports/trivy-go-initial.json \
            --dockerfile-report trivy-reports/trivy-dockerfile-initial.json \
            --image-report trivy-reports/trivy-image-initial.json
        continue-on-error: true

      - name: Commit & push remediation changes
        if: ${{ always() }}
        run: |
          git_status=$(git status --porcelain)
          if [ -n "$git_status" ]; then
            echo "::notice::Remediation applied—committing changes back to $GITHUB_REF_NAME"
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add go-app-vulnerable/
            git commit -m "chore(security): automated vulnerability remediation"
            git push origin HEAD:"${GITHUB_REF#refs/heads/}"
          else
            echo "::notice::No remediation changes detected—nothing to commit."
          fi

      - name: Build Docker Image (Post-Remediation)
        run: docker build -t go-app-vulnerable:autofix-latest ./go-app-vulnerable/

      - name: Re-scan after Remediation
        run: |
          trivy fs  --format json --output trivy-reports/trivy-go-recheck.json \
            --severity CRITICAL,HIGH,MEDIUM,LOW go-app-vulnerable/
          trivy config --format json --output trivy-reports/trivy-dockerfile-recheck.json \
            --severity CRITICAL,HIGH,MEDIUM,LOW go-app-vulnerable/Dockerfile
          trivy image --format json --output trivy-reports/trivy-image-recheck.json \
            --severity CRITICAL,HIGH,MEDIUM,LOW go-app-vulnerable:autofix-latest
        continue-on-error: true

      - name: Upload Post-Remediation SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-reports/trivy-fs.sarif
        if: always()
