name: Automated Vulnerability Remediation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trivy_scan_and_fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git-auto-commit

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # - name: Install Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y wget docker.io

      - name: Install Trivy
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Run Trivy Scans
        run: |
          trivy fs . --format json --output trivy-fs-report.json
          trivy config . --format json --output trivy-config-report.json
          trivy image myapp:latest --format json --output trivy-image-report.json

      - name: Run Remediation Script
        run: |
          python .github/scripts/remediate_pipeline_poc.py \
            --go-report trivy-fs-report.json \
            --docker-report trivy-config-report.json \
            --image-report trivy-image-report.json

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-remediated vulnerabilities using Trivy suggestions"
          commit_user_name: "Security Bot"
          commit_user_email: "security@example.com"

      - name: Generate Final SARIF Report
        run: |
          trivy fs . --format sarif --output trivy-fs-final.sarif
          trivy config . --format sarif --output trivy-config-final.sarif
          trivy image myapp:latest --format sarif --output trivy-image-final.sarif

      - name: Upload SARIF file to GitHub CodeQL
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs-final.sarif,trivy-config-final.sarif,trivy-image-final.sarif
          checkout_path: /home/runner/work/PoC-AE/PoC-AE
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true

      - name: Upload Remediation Report
        uses: actions/upload-artifact@v4
        with:
          name: remediation-report
          path: remediation-report.md